### ISSUE TITLE
Simple server throws error from bunrest module

### ISSUE THREAD

**Issue by hankatola** [lau1944/bunrest#17]
The following code
```javascript
import server from `bunrest`
const app = server()
app.get(`/`, (req,res) => {
  res.status(200).json({message: `hello world`})
})
app.listen(8888, ()=>{
  console.log(`Listening on port 8888`)
})
```
triggers the following logs when the route is hit
```bash
(base) [dp@fedora bunrest]$ bun run server.js 
/
Listening on port 8888
235 |     searchParams.forEach((v, k) => {
236 |       newReq.query[k] = v;
237 |     });
238 | 
239 |     // append body
240 |     const body: { [key: string]: any } = await req.json();
                                                   ^
SyntaxError: Unexpected end of JSON input
      at /home/dp/dev/bun/bunrest/node_modules/bunrest/src/server/server.ts:240:47
      at bunRequest (/home/dp/dev/bun/bunrest/node_modules/bunrest/src/server/server.ts:222:27)
      at /home/dp/dev/bun/bunrest/node_modules/bunrest/src/server/server.ts:132:38
      at fetch (/home/dp/dev/bun/bunrest/node_modules/bunrest/src/server/server.ts:131:33)
GET - http://127.0.0.1:8888/ failed
^C
(base) [dp@fedora bunrest]$ 
```

**Comment by LuisMalhadas** [comment]
I have the same issue running the 0.8.1 bun and bunrest 1.2.1

**Comment by lau1944** [comment]
Merged.

**Comment by ashih42** [comment]
I still get the exact same error with the above example, on bun 1.0.0, bunrest 1.2.1.

**Comment by LuisMalhadas** [comment]
> I still get the exact same error with the above example, on bun 1.0.0, bunrest 1.2.1.

could it be related to this: [bun/#2477](https://github.com/oven-sh/bun/issues/2477)
